--DROP TABLE IF EXISTS items;

CREATE TABLE IF NOT EXISTS items (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    list_id NOT NULL,
    created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    email TEXT NOT NULL,
    title TEXT NOT NULL,
    url TEXT NOT NULL,
    DL Text,
    FOREIGN KEY (list_id) REFERENCES usr (id)
);
